name: Test

on: [workflow_dispatch, push]

jobs:
  find-files:
    runs-on: ubuntu-latest
    outputs: 
      added: ${{ steps.abc.outputs.added }}
      modified: ${{ steps.abc.outputs.modified }}
      removed: ${{ steps.abc.outputs.removed }}
    steps:
      - uses: actions/checkout@v3
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: csv
          token: ${{ secrets.GITHUB_TOKEN }}
  show-files:
    needs: find-files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Read From Previous Job
        run: echo ${{needs.find-files.outputs.added}}
      - name: Install Python Requirements
        run: pip install -r Parser/requirements.txt

 #         echo "All:"
 #         echo "${{ steps.abc.outputs.all }}"
 #         echo "Added:"
 #         echo "${{ steps.abc.outputs.added }}"
 #         echo "Removed:"
 #         echo "${{ steps.abc.outputs.removed }}"
 #         echo "Renamed:"
 #         echo "${{ steps.abc.outputs.renamed }}"
 #         echo "Modified:"
 #         echo "${{ steps.abc.outputs.modified }}"
 #         echo "Added+Modified:"
 #         echo "${{ steps.abc.outputs.added_modified }}"
